datasets:
  # - name: CUB_200_2011
  # - name: Flower102
  # - name: wds_cars
  # - name: wds_fgvc_aircraft
  # - name: wds_food101
  # - name: wds_imagenetv2
  - name: wds_objectnet # too large
  # # - name: wds_sun397 # too large
  # - name: wds_vtab-cifar100
  # - name: wds_vtab-pets
  # - name: wds_vtab-resisc45


models:
  - name: openai/clip-vit-base-patch32
  # - name: google/siglip-large-patch16-384
  # - name: facebook/flava-full
  
consistency_scorer:
  enable: True
  top_k_values: [1, 3, 5, 10, 20, 50, 100, null]  # null means consider all classes
  # top_k_values: [null]
  # num_embed_cutoff_values: [1, 3, 5, 10, 20, null]  # null means use all embeddings
  num_embed_cutoff_values: [1, 3, 5, 10, 20, null]
  
experiment_params:
  batch_size: 64
  knn_batch_size: 1024
  num_captions: 35
  tsne_perplexity: 30
  tsne_n_iter: 1000
  top_k_classes: 12
  pseudo_data: False # set to False
  save_results: True
  results_dir: results/
  enable_plot: False # set to False


gpt_model:
  name: 'gpt-4o-2024-11-20'
  # name: 'gpt-4.1-mini-2025-04-14'
  # name: 'gpt-4.1-2025-04-14'