classes = [
    'adonis',
    'african giant swallowtail',
    'american snoot',
    'an 88',
    'appollo',
    'arcigera flower moth',
    'atala',
    'atlas moth',
    'banded orange heliconian',
    'banded peacock',
    'banded tiger moth',
    'beckers white',
    'bird cherry ermine moth',
    'black hairstreak',
    'blue morpho',
    'blue spotted crow',
    'brookes birdwing',
    'brown argus',
    'brown siproeta',
    'cabbage white',
    'cairns birdwing',
    'chalk hill blue',
    'checquered skipper',
    'chestnut',
    'cinnabar moth',
    'clearwing moth',
    'cleopatra',
    'clodius parnassian',
    'clouded sulphur',
    'comet moth',
    'common banded awl',
    'common wood-nymph',
    'copper tail',
    'crecent',
    'crimson patch',
    'danaid eggfly',
    'eastern coma',
    'eastern dapple white',
    'eastern pine elfin',
    'elbowed pierrot',
    'emperor gum moth',
    'garden tiger moth',
    'giant leopard moth',
    'glittering sapphire',
    'gold banded',
    'great eggfly',
    'great jay',
    'green celled cattleheart',
    'green hairstreak',
    'grey hairstreak',
    'hercules moth',
    'humming bird hawk moth',
    'indra swallow',
    'io moth',
    'iphiclus sister',
    'julia',
    'large marble',
    'luna moth',
    'madagascan sunset moth',
    'malachite',
    'mangrove skipper',
    'mestra',
    'metalmark',
    'milberts tortoiseshell',
    'monarch',
    'mourning cloak',
    'oleander hawk moth',
    'orange oakleaf',
    'orange tip',
    'orchard swallow',
    'painted lady',
    'paper kite',
    'peacock',
    'pine white',
    'pipevine swallow',
    'polyphemus moth',
    'popinjay',
    'purple hairstreak',
    'purplish copper',
    'question mark',
    'red admiral',
    'red cracker',
    'red postman',
    'red spotted purple',
    'rosy maple moth',
    'scarce swallow',
    'silver spot skipper',
    'sixspot burnet moth',
    'sleepy orange',
    'sootywing',
    'southern dogface',
    'straited queen',
    'tropical leafwing',
    'two barred flasher',
    'ulyses',
    'viceroy',
    'white lined sphinx moth',
    'wood satyr',
    'yellow swallow tail',
    'zebra long wing'
]

label_to_class = {i: label for i, label in enumerate(classes)}