cifar_category_map = {
    "beaver": "aquatic mammals", "dolphin": "aquatic mammals", "otter": "aquatic mammals", 
    "seal": "aquatic mammals", "whale": "aquatic mammals",
    "aquarium fish": "fish", "flatfish": "fish", "ray": "fish", "shark": "fish", "trout": "fish",
    "orchid": "flowers", "poppy": "flowers", "rose": "flowers", "sunflower": "flowers", "tulip": "flowers",
    "bottle": "food containers", "bowl": "food containers", "can": "food containers", "cup": "food containers", 
    "plate": "food containers",
    "apple": "fruit and vegetables", "mushroom": "fruit and vegetables", "orange": "fruit and vegetables", 
    "pear": "fruit and vegetables", "sweet pepper": "fruit and vegetables",
    "clock": "household electrical devices", "keyboard": "household electrical devices", 
    "lamp": "household electrical devices", "telephone": "household electrical devices", 
    "television": "household electrical devices",
    "bed": "household furniture", "chair": "household furniture", "couch": "household furniture", 
    "table": "household furniture", "wardrobe": "household furniture",
    "bee": "insects", "beetle": "insects", "butterfly": "insects", "caterpillar": "insects", "cockroach": "insects",
    "bear": "large carnivores", "leopard": "large carnivores", "lion": "large carnivores", "tiger": "large carnivores", 
    "wolf": "large carnivores",
    "bridge": "large man-made outdoor things", "castle": "large man-made outdoor things", 
    "house": "large man-made outdoor things", "road": "large man-made outdoor things", "skyscraper": "large man-made outdoor things",
    "cloud": "large natural outdoor scenes", "forest": "large natural outdoor scenes", "mountain": "large natural outdoor scenes", 
    "plain": "large natural outdoor scenes", "sea": "large natural outdoor scenes",
    "camel": "large omnivores and herbivores", "cattle": "large omnivores and herbivores", 
    "chimpanzee": "large omnivores and herbivores", "elephant": "large omnivores and herbivores", 
    "kangaroo": "large omnivores and herbivores",
    "fox": "medium-sized mammals", "porcupine": "medium-sized mammals", "possum": "medium-sized mammals", 
    "raccoon": "medium-sized mammals", "skunk": "medium-sized mammals",
    "crab": "non-insect invertebrates", "lobster": "non-insect invertebrates", "snail": "non-insect invertebrates", 
    "spider": "non-insect invertebrates", "worm": "non-insect invertebrates",
    "baby": "people", "boy": "people", "girl": "people", "man": "people", "woman": "people",
    "crocodile": "reptiles", "dinosaur": "reptiles", "lizard": "reptiles", "snake": "reptiles", "turtle": "reptiles",
    "hamster": "small mammals", "mouse": "small mammals", "rabbit": "small mammals", "shrew": "small mammals", 
    "squirrel": "small mammals",
    "maple tree": "trees", "oak tree": "trees", "palm tree": "trees", "pine tree": "trees", "willow tree": "trees",
    "bicycle": "vehicles", "bus": "vehicles", "motorcycle": "vehicles", "pickup truck": "vehicles", 
    "train": "vehicles",
    "lawn mower": "vehicles", "rocket": "vehicles", "streetcar": "vehicles", "tank": "vehicles", 
    "tractor": "vehicles"
}